configured_endpoints: 43
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-8da3ca8d908c1cb7ac075bfe580fef95dfb037faa4e205aec6d82efceed6b480.yml
openapi_spec_hash: 42cff4903dab42a1c6d8090b4a2272cb
config_hash: 87275e969233e820f1dc669b9c589bda
