configured_endpoints: 65
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-56e102abfc629cc192c1aec77fe5f4ed35978f859daaedc75bc73fe1032e3f9f.yml
openapi_spec_hash: 5718229a23e71539d9ad0cba0fa37d7a
config_hash: 4afa0a81ae82fc9361b736bda89c95b5
