configured_endpoints: 48
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-8fb495168a7e4b3821998ed80ba2c4def48bea531eb95ce7c1d35e87c082624c.yml
openapi_spec_hash: ae84c4c9e3bfeededa8fe51356bfae8a
config_hash: 7f0f74d9e97d2aca5efae43af2aad1d5
