configured_endpoints: 66
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-4fde3c4b67331eb3fc0cd68ca2eb7ec5769835299eeacf12f76ba6119e2eb681.yml
openapi_spec_hash: b044b0f672b1afce745cc8d26ae7c99d
config_hash: 6bfbf92d1ac1f871d9a4f0e50b1938eb
