configured_endpoints: 65
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-4fde3c4b67331eb3fc0cd68ca2eb7ec5769835299eeacf12f76ba6119e2eb681.yml
openapi_spec_hash: b044b0f672b1afce745cc8d26ae7c99d
config_hash: 98b80bfa3e05ea5ff49dacd67a21fc95
