configured_endpoints: 48
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-9d4de1c8fbc7bfd1f3bc3a6021c75cf0b6b0af0c31bfb380fc5fca21bcf9b00f.yml
openapi_spec_hash: b7c5124a582eedad208ab50fac4e8c16
config_hash: 7f0f74d9e97d2aca5efae43af2aad1d5
