configured_endpoints: 52
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-f8a5fc686bf465f9e68e8d436e5d0c64bf53faf45b33cce251bbf454ec225fd1.yml
openapi_spec_hash: cf7ff86ade5074e942f73f84ff9fb0b5
config_hash: 7aaf577b8fbb75f38e64efcd6d79a4b1
