configured_endpoints: 49
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-5dd1fc1d80d7eed625067ac0cd1e1e279977d2fa1e4bbfb2ac3fadbe19b172af.yml
openapi_spec_hash: 55f5738f8ead4f271b187b1b4c2b162c
config_hash: c61030cf34e7f279c8dce04f68df11b8
