configured_endpoints: 60
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-9ace6e4b75e6f577cea4afda9ee565ab318769fa446ab185aec2bd28a1a281d0.yml
openapi_spec_hash: a7e81de26cddf6e773fa5580fe113ef4
config_hash: 00f6d7577a558c5e19cc566cd61ae0e1
