configured_endpoints: 65
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-d1d5a16416b17ae491f833ccbaff387d4f89f25b8cb3b8e8a7e4c1ea4742b0b5.yml
openapi_spec_hash: 72ac85fbee2eb3655ee0eac80a867644
config_hash: 4afa0a81ae82fc9361b736bda89c95b5
