configured_endpoints: 48
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-ab609d9d247623bffb9503a378fdf019c33f19e616abdeb9e7346d1ac245d50e.yml
openapi_spec_hash: e8c11cca03275b25a2f65c9cf6edab9f
config_hash: 7f0f74d9e97d2aca5efae43af2aad1d5
