configured_endpoints: 48
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/composio-alt-glitch%2Fcomposio-sdk-3a5c055baf1737acd214c4f1fa26cabc916c9fe3e1080afc94c1acff0516f7a9.yml
openapi_spec_hash: f4f4af23bd2441d0ebfac8121055eca8
config_hash: 7f0f74d9e97d2aca5efae43af2aad1d5
